### ISSUE TITLE
Performance Chrome Vs. Firefox

### ISSUE THREAD

**Issue by pepperav** [kripken/sql.js#126] opened 2015-12-17 10:46 UTC
Hi,
casually I've noticed a very different performance between these two browser.
In fact, executing GUI demo page into Firefox, it processes code fastest Chrome.
This behaviour is the same of my web app using your library.
I use Chrome 47.0.2526.106 m and Firefox 43.0.

Do you know why exist this problem?
Regards

**Comment by lovasoa** [comment] 2015-12-17 12:27
This "problem" exists because [chrome doesn't implement `asm.js` yet](https://bugs.chromium.org/p/v8/issues/detail?id=2599).

**Comment by wxv** [comment] 2015-12-25 00:52
The difference in performance is huge. In Firefox, an SQL SELECT on a large table takes less than 0.2 seconds, whereas in chrome it takes more than 10 seconds. I hope chrome will use `asm.js` soon.

**Comment by lovasoa** [comment] 2015-12-25 07:36
Then you should report the bug to chrome.

**Comment by Avinashachu007** [comment] 2016-07-14 10:47
I tried a basic Query on Firefox as well as Chrome
`SELECT name, sql
  FROM sqlite_master
  WHERE type='table';`

RESULTS
FF:  Executing SQL: 6.540000000008149ms 
         Displaying results: 0.6900000000023283ms

Chrome: Executing SQL: 14.35999999998603ms 
              Displaying results: 0.6300000000046566ms




Later this Query:
DROP TABLE IF EXISTS employees;
CREATE TABLE employees( id          integer,  name    text,
                          designation text,     manager integer,
                          hired_on    date,     salary  integer,
                          commission  float,    dept    integer);

  INSERT INTO employees VALUES (1,'JOHNSON','ADMIN',6,'12-17-1990',18000,NULL,4);
  INSERT INTO employees VALUES (2,'HARDING','MANAGER',9,'02-02-1998',52000,300,3);
  INSERT INTO employees VALUES (3,'TAFT','SALES I',2,'01-02-1996',25000,500,3);
  INSERT INTO employees VALUES (4,'HOOVER','SALES I',2,'04-02-1990',27000,NULL,3);
  INSERT INTO employees VALUES (5,'LINCOLN','TECH',6,'06-23-1994',22500,1400,4);
  INSERT INTO employees VALUES (6,'GARFIELD','MANAGER',9,'05-01-1993',54000,NULL,4);
  INSERT INTO employees VALUES (7,'POLK','TECH',6,'09-22-1997',25000,NULL,4);
  INSERT INTO employees VALUES (8,'GRANT','ENGINEER',10,'03-30-1997',32000,NULL,2);
  INSERT INTO employees VALUES (9,'JACKSON','CEO',NULL,'01-01-1990',75000,NULL,4);
  INSERT INTO employees VALUES (10,'FILLMORE','MANAGER',9,'08-09-1994',56000,NULL,2);
  INSERT INTO employees VALUES (11,'ADAMS','ENGINEER',10,'03-15-1996',34000,NULL,2);
  INSERT INTO employees VALUES (12,'WASHINGTON','ADMIN',6,'04-16-1998',18000,NULL,4);
  INSERT INTO employees VALUES (13,'MONROE','ENGINEER',10,'12-03-2000',30000,NULL,2);
  INSERT INTO employees VALUES (14,'ROOSEVELT','CPA',9,'10-12-1995',35000,NULL,1);

SELECT designation,COUNT(*) AS nbr, (AVG(salary)) AS avg_salary FROM employees GROUP BY designation ORDER BY avg_salary DESC;
SELECT name,hired_on FROM employees ORDER BY hired_on;

Chrome: **Executing SQL: 1178.25ms**
 Displaying results: 2.5399999999999636ms**
FF:Executing SQL: **43.73999999999978ms** 
Displaying results: 1.0450000000000728ms

**Comment by lovasoa** [comment] 2016-07-14 12:12
These results aren't really representative of what performance would be on a real-life use case, as it seems the requests have been submitted after a "cold start". Try executing a few different requests first, and then start measuring time. The results should be very different.

**Comment by TobiasNickel** [comment] 2016-07-15 01:46
so I think the same issue as in chrome will be in node.js

**Comment by hfhchan** [comment] 2016-07-28 02:40
@Avinashachu007  if you have the appropriate indexes created on designation, avg_salary and hired_on, the query will execute much faster on either Firefox or Chrome.

**Comment by maksimdegtyarev** [comment] 2016-07-28 06:28
@hfhchan How can I create indexes for table columns?

**Comment by hfhchan** [comment] 2016-07-28 06:36
Using CREATE INDEX:
https://www.sqlite.org/lang_createindex.html

**Comment by dinedal** [comment] 2016-11-15 06:24
Closing this as resolved for now.

Ideally we have some sort of cross browser benchmark suite, but I'm not aware of any free headless browser services we could run it on.

**Closed by dinedal** 2016-11-15 06:24 UTC
