### ISSUE TITLE
infinite cpu-eating loop on this query..

### ISSUE THREAD

**Issue by divinity76** [kripken/sql.js#130] opened 2016-01-03 23:18 UTC
in chrome 47.0.2526.106 m 32bit build, windows 7 x64, on http://kripken.github.io/sql.js/GUI/  execute the following query about 5-10 times, and it will _ALWAYS_ hang in an infinite cpu-eating loop, generating no results, after a couple of tries.  

```sql
DROP TABLE IF EXISTS `ips`;
CREATE TABLE `ips` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `ip` INTEGER NOT NULL DEFAULT NULL,
  `scantime` INTEGER NULL DEFAULT NULL,
  `pingable` INTEGER NULL DEFAULT NULL
);

INSERT INTO `ips` (`ip`,`scantime`,`pingable`) VALUES (random(),random(),0);

SELECT * FROM `ips`;
```

this does NOT reproduce on Firefox 43.0.3 32bit, NOT Internet Explorer 11 x64, but Google Chrome, both on Debian Linux 8 x64 with 64bit build, and Windows 7 x64 with 32bit build (both being chrome version 47-something)

**Comment by dinedal** [comment] 2016-03-11 06:47
Chrome Version 48.0.2564.116 (64-bit)

Unable to reproduce this.

**Comment by divinity76** [comment] 2016-03-11 16:35
same here, can not reproduce on 49.0.2623.75 m - and i no longer have any computer with 47 ^^

**Comment by lovasoa** [comment] 2016-03-11 16:38
Let's close it then, we'll reopen it if needed.

**Closed** 2016-03-11 16:38 UTC
