### ISSUE TITLE
Are transactions supported?

### ISSUE THREAD

**Issue by AleCaste** [kripken/sql.js#116] opened 2015-07-27 01:21 UTC
Hello,
Are transactions supposed to work with this library?
I have tried to use them (basically I tried to run a 'BEGIN TRANSACTION' command then an 'INSERT' and then a 'ROLLBACK') and the test is not working for me.

**Comment by screendriver** [comment] 2015-09-08 04:38
+1

**Comment by chalkers** [comment] 2015-11-25 23:11
Yeah I'm having strange issues with this.
For example, `ROLLBACK;` actually nixes the whole database.

**Comment by lovasoa** [comment] 2015-11-26 06:29
Could you please provide a sequence of statements that triggers this bug ?

**Comment by jayralencar** [comment] 2016-05-24 14:34
+1

**Comment by L3V147H4N** [comment] 2016-07-23 01:34
+1

**Comment by dinedal** [comment] 2016-11-15 06:01
Transactions are a pretty important part of sqlite's feature set. I want to make sure we do not have an issue with them.

I have written a test using them here in an attempt to reproduce: https://github.com/kripken/sql.js/pull/177

While I admit it is a pretty basic use of transactions, it does pass. I even checked @chalkers statement that `ROLLBACK` deletes the entire database.

If you can please write a test that reproduces the issue I will happily investigate the cause.

Since I am unable to reproduce I will close this issue for now.

**Closed by dinedal** 2016-11-15 06:01 UTC
